spring:
 application:
  name: JPAAuthApp
 datasource:
  url: jdbc:mysql://localhost:3306/springSecurity
  username: root
  password: root
  initialization-mode: ALWAYS 
 jpa:
  hibernate:
   ddl-auto: create
  show-sql: true
   
       
server:
  port: 8082